name: Testing

on:
  push:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Run Rust example
        run: cargo run --example test

      - name: Check system meory
        run: vm_stat
